name             'mssqlserver'
maintainer       'Standard Edge'
maintainer_email 'support@standardedge.com'
license          'All rights reserved'
description      'Configures mssqlserver'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends			 'windows'
depends      'powershell'
depends      'windows_firewall'